# version: "3" - версия убрана, т.к. вызывала предупреждение
services:
  telegram-bot:
    image: sail-8.4/app
    restart: unless-stopped
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      CONTAINER_ROLE: "telegram-bot"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    volumes:
      - ".:/var/www/html"
      - "telegram-bot-data:/var/www/html/storage/telegram"
    networks:
      - default
    depends_on:
      - laravel.test
      - mysql
    healthcheck:
      test: ["CMD", "php", "artisan", "telegram:basic-test"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: php artisan telegram:standalone
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: ict_sail
    external: true

volumes:
  telegram-bot-data:
    driver: local
